server:
  port: 8081

spring:
  application:
    name: account-service
  datasource:
    url: jdbc:h2:file:./runtime-data/account/account-service;AUTO_SERVER=FALSE
    username: sa
    password: ""
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/account/schema.sql
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
